### ISSUE TITLE
2 step form example, how to link back to step 1?

### ISSUE THREAD

**Issue by finalwebsites** [ibericode/html-forms-code-snippets#1]
Hi Danny,

nice feature!

I would like to create a second button to step 2 to give the user the option to go back 1 step.
Leaving the value empty doesn't help :(

**Comment by dannyvankooten** [comment]
Hey Olaf,

Sorry, just seeing this now. Just pushed out an update to HTML Forms to make this possible, along with an example on how to do this.

Cheers!

**Comment by finalwebsites** [comment]
Hi Danny, you are the best. Thanks

Op ma 6 aug. 2018 16:34 schreef Danny van Kooten <notifications@github.com>:
